Write reminder to upgrade to Node.js v18
Initially, there was an attempt to use 'node18'
argument, but that throwed an error:
Error: System.ArgumentOutOfRangeException: Specified argument was out of
  the range of valid values. (Parameter ''using: node18' is not supported,
  use 'docker', 'node12' or 'node16' instead.')